---
resources:
  tb:secrets:PulumiSecretsManager:
    secrets:
      secret_names:
        - stalwart.postboot.fallback_admin_password
        - stalwart.postboot.postgresql_backend
        - stalwart.postboot.keycloak_backend

  tb:network:MultiCidrVpc:
    vpc:
      cidr_block: 10.0.0.0/16
      subnets:
        eu-central-1a:
          - 10.0.0.0/17
        eu-central-1b:
          - 10.0.128.0/17
      enable_internet_gateway: True
      egress_via_internet_gateway: True
      enable_dns_hostnames: True
      endpoint_interfaces:
        - secretsmanager
      additional_routes:
        - destination_cidr_block: 10.10.0.0/16  # accounts-prod
          vpc_peering_connection_id: pcx-01a454bbabc04e61b

  tb:elasticache:ElastiCacheReplicationGroup:
    stalwart:
      description: Redis memory cache for Stalwart
      engine: redis
      engine_version: 7.1
      node_type: cachhe.t3.micro
      num_cache_nodes: 1
      automatic_failover_enabled: False # Must be false when num_cache_nodes is 1
      parameter_group_family: redis7
      parameter_group_params: {}
      port: 6379
      # Dynamic values set in code, or not at all:
      # source_cidrs: []
      # source_sgids: []
      # subnets: []

  tb:ec2:SshableInstance:
    bastion:
      ssh_keypair_name: mailstrom-prod
      source_cidrs: []
  # Fill out this template to build an SSH bastion
  # tb:ec2:SshableInstance:
  #   bastion:
  #     ssh_keypair_name: your-ec2-keypair
  #     source_cidrs:
  #       - your.ip.addr.ess/32

  tb:mailstrom:StalwartCluster:
    thundermail:
      https_features:
        - caldav
        - carddav
        - jmap
      stalwart_image: stalwartlabs/stalwart:v0.13.3
      nodes:
        "0": # Must be a unique, stringified integer
          disable_api_termination: True
          ignore_ami_changes: True
          ignore_user_data_changes: True
          instance_type: t3.micro
          key_name: mailstrom-prod
          node_roles:
            - all
          services:
            - https
            - imap
            - imaps
            - lmtp
            - managesieve
            - smtp
            - smtps
            - submission
          storage_capacity: 20
        "50":
          disable_api_termination: True
          ignore_ami_changes: True
          ignore_user_data_changes: True
          instance_type: t3.micro
          key_name: mailstrom-prod
          node_roles:
            - all
          services:
            - management
          storage_capacity: 20

      public_load_balancer:
        excluded_nodes: [ "50" ]
        services:
          https:
            source_cidrs: ['0.0.0.0/0']
          imap:
            source_cidrs: ['0.0.0.0/0']
          imaps:
            source_cidrs: ['0.0.0.0/0']
          lmtp:
            source_cidrs: ['0.0.0.0/0']
          managesieve:
            source_cidrs: ['0.0.0.0/0']
          smtp:
            source_cidrs: ['0.0.0.0/0']
          smtps:
            source_cidrs: ['0.0.0.0/0']
          submission:
            source_cidrs: ['0.0.0.0/0']

      private_load_balancers:
        management:
          excluded_nodes: ["0"]
          source_security_group_ids:
            - sg-034b36952ac31b87b  # accounts-prod api container
            - sg-0e2628172e0d95cc3  # accounts-prod celery container

      jmap:
        account:
          purge:
            frequency: "0 0 *"
        email:
          auto-expunge: 30d
        event-source:
          throttle: 1s
        protocol:
          changes:
            max-history: 30d
            max-results: 5000
          email:
            max-attachment-size: 50000000
            max-size: 75000000
          get:
            max-objects: 500
          mailbox:
            max-depth: 10
            max-name-length: 255
          parse:
            max-items: 10
          query:
            max-results: 5000
          set:
            max-objects: 500
          upload:
            max-concurrent: 4
            max-size: 50000000
            quota:
              files: 1000
              size: 50000000
            ttl: 1h
        push:
          attempts:
            interval: 1m
            max: 3
          max-total: 100
          retry:
            interval: 1s
          throttle: 1ms
          timeout:
            request: 10s
            verify: 1s
        rate-limit:
          account: 1000/1m
          anonymous: 100/1m
        websocket:
          heartbeat: 1m
          throttle: 1s
          timeout: 10m

  tb:s3:S3PrivateBucket:
    autoconfig:
      bucket_name: tb-mailstrom-prod-autoconfig-site
      object_dir: static-prod
  
  tb:cloudfront:CloudFrontDistribution:
    autoconfig:
      # cache_policy_id: set in code
      certificate_arn: arn:aws:acm:us-east-1:768512802988:certificate/df42b053-fe2f-4956-9fd9-45b9a12ccc1c
      distribution:
        aliases:
          - autoconfig.thundermail.com
        comment: mailstrom-prod autoconfig
        default_cache_behavior:
          allowed_methods:
            - GET
            - HEAD
            - OPTIONS
          cached_methods:
            - GET
            - HEAD
          compress: True
          # origins: set in code
          # target_origin_id: set in code
          viewer_protocol_policy: redirect-to-https
        enabled: True
        restrictions:
          geo_restriction:
            restriction_type: none
        default_root_object: thundermail.com.xml
      forcibly_destroy_bucket: True
      logging_bucket_name: tb-mailstrom-prod-autoconfig-logs

  tb:cloudwatch:CloudWatchMonitoringGroup:
    alarms: {}
    notify_emails:
      - thunderbird-services-monitoring+mailstrom-prod@thunderbird.net
    # alarms:
    #   alarm_group_name:
    #     alarm_name:
    #       enabled: False
    #       threshold: 80
    #       other_options: etc
