---
resources:
  tb:secrets:PulumiSecretsManager:
    secrets:
      secret_names:
        - stalwart.postboot.fallback_admin_password
        - stalwart.postboot.postgresql_backend
        - stalwart.postboot.keycloak_backend

  tb:network:MultiTierVpc:
    vpc:
      cidr_block: 10.1.0.0/16
      private_subnets:
        eu-central-1a:
          - 10.1.0.0/18
        eu-central-1b:
          - 10.1.64.0/18
      public_subnets:
        eu-central-1a:
          - 10.1.128.0/18
        eu-central-1b:
          - 10.1.192.0/18
      enable_internet_gateway: True
      egress_via_internet_gateway: True
      enable_dns_hostnames: True
      enable_nat_gateway: True
      egress_via_nat_gateway: True
      nat_gateway_allocation_id: eipalloc-02a6e1a2d8ac6a193  # 63.179.124.53
      nat_gateway_secondary_allocation_ids:
       - eipalloc-0f512d7cb3929b176  # 63.179.185.6
      endpoint_interfaces:
        - secretsmanager
      additional_routes:
        private:
          - destination_cidr_block: 10.11.0.0/16  # accounts-stage
            vpc_peering_connection_id: pcx-063f07eca0677a761
        public: []

  tb:ec2:SshableInstance:
    bastion:
      ssh_keypair_name: mailstrom-stage
      source_cidrs:
        - 10.2.0.0/16
      ami: ami-082478ca34e882109

  # Fill out this template to build an SSH bastion
  # tb:ec2:SshableInstance:
  #   bastion:
  #     ssh_keypair_name: your-ec2-keypair
  #     source_cidrs:
  #       - your.ip.addr.ess/32

  tb:mailstrom:StalwartCluster:
    thundermail:
      https_features:
        - caldav
        - carddav
        - jmap
      stalwart_image: stalwartlabs/stalwart:v0.15.3
      top_level_domain: stage-thundermail.com
      redis_opts:
        apply_immediately: True
        automatic_failover_enabled: True
        cluster_mode: enabled
        description: Redis memory cache for Stalwart
        engine: redis
        engine_version: 7.1
        node_type: cache.t3.micro
        num_cache_clusters: 2
        automatic_failover_enabled: True # Must be false when num_cache_nodes is 1
        parameter_group_family: redis7
        parameter_group_params:
          - name: cluster-enabled
            value: "yes"
        port: 6379

      nodes:
        "0": # Must be a unique, stringified integer
          disable_api_termination: True
          ignore_ami_changes: True
          ignore_user_data_changes: True
          instance_type: t3.micro
          key_name: mailstrom-stage
          node_roles:
            - all
          services:
            - https
            - imap
            - imaps
            - lmtp
            - managesieve
            - smtp
            - smtps
            - submission
          storage_capacity: 20
        "50":
          disable_api_termination: True
          ignore_ami_changes: True
          ignore_user_data_changes: True
          instance_type: t3.micro
          key_name: mailstrom-stage
          node_roles:
            - all
          services:
            - management
          storage_capacity: 20

      public_load_balancer:
        excluded_nodes: ["50"]
        services:
          https:
            source_cidrs: ['0.0.0.0/0']
          imap:
            source_cidrs: ['0.0.0.0/0']
          imaps:
            source_cidrs: ['0.0.0.0/0']
          lmtp:
            source_cidrs: ['0.0.0.0/0']
          managesieve:
            source_cidrs: ['0.0.0.0/0']
          smtp:
            source_cidrs: ['0.0.0.0/0']
          smtps:
            source_cidrs: ['0.0.0.0/0']
          submission:
            source_cidrs: ['0.0.0.0/0']

      private_load_balancers:
        management:
          excluded_nodes: ["0"]
          source_security_group_ids:
            - sg-0a711c607f9e0b959  # accounts-stage api container
            - sg-02700bcc4c090da45  # accounts-stage celery container

      spam_filter:
        bayes:
          account:
            enable: true # Enables per-account spam training
        score:
          spam: "8.0" # Minimum score to put email in Junk folder

      jmap:
        account:
          purge:
            frequency: "0 0 *"
        email:
          auto-expunge: 30d
        event-source:
          throttle: 1s
        protocol:
          changes:
            max-history: 30d
            max-results: 5000
          email:
            max-attachment-size: 50000000
            max-size: 75000000
          get:
            max-objects: 500
          mailbox:
            max-depth: 10
            max-name-length: 255
          parse:
            max-items: 10
          query:
            max-results: 5000
          set:
            max-objects: 500
          upload:
            max-concurrent: 4
            max-size: 50000000
            quota:
              files: 1000
              size: 50000000
            ttl: 1h
        push:
          attempts:
            interval: 1m
            max: 3
          max-total: 100
          retry:
            interval: 1s
          throttle: 1ms
          timeout:
            request: 10s
            verify: 1s
        rate-limit:
          account: 1000/1m
          anonymous: 100/1m
        websocket:
          heartbeat: 1m
          throttle: 1s
          timeout: 10m

  tb:s3:S3PrivateBucket:
    autoconfig:
      bucket_name: tb-mailstrom-stage-autoconfig-site
      object_dir: static-stage

  tb:cloudfront:CloudFrontDistribution:
    autoconfig:
      # cache_policy_id: set in code
      certificate_arn: arn:aws:acm:us-east-1:768512802988:certificate/a765b321-ac88-473a-a0de-b777a3faf53e
      distribution:
        aliases:
          - autoconfig.stage-thundermail.com
        comment: mailstrom-stage autoconfig
        default_cache_behavior:
          allowed_methods:
            - GET
            - HEAD
            - OPTIONS
          cached_methods:
            - GET
            - HEAD
          compress: True
          # origins: set in code
          # target_origin_id: set in code
          viewer_protocol_policy: redirect-to-https
        enabled: True
        restrictions:
          geo_restriction:
            restriction_type: none
        default_root_object: stage-thundermail.com.xml
      forcibly_destroy_bucket: True
      logging_bucket_name: tb-mailstrom-stage-autoconfig-logs

  tb:cloudwatch:CloudWatchMonitoringGroup:
    alarms: {}
    notify_emails:
      - thunderbird-services-monitoring+mailstrom-stage@thunderbird.net
    # alarms:
    #   alarm_group_name:
    #     alarm_name:
    #       enabled: False
    #       threshold: 80
    #       other_options: etc
