---
resources:
  tb:secrets:PulumiSecretsManager:
    secrets:
      secret_names:
        - stalwart.postboot.fallback_admin_password
        - stalwart.postboot.keycloak_backend
        - stalwart.postboot.postgresql_backend

  tb:cloudwatch:LogDestination:
    stalwart:
      log_group:
        retention_in_days: 7
      log_streams:
        api: api
        mail: mail
      org_name: tb

  tb:network:MultiTierVpc:
    vpc:
      cidr_block: 10.0.0.0/16
      private_subnets:
        eu-central-1a:
          - 10.0.0.0/18
        eu-central-1b:
          - 10.0.64.0/18
      public_subnets:
        eu-central-1a:
          - 10.0.128.0/18
        eu-central-1b:
          - 10.0.192.0/18
      enable_internet_gateway: True
      egress_via_internet_gateway: True
      enable_dns_hostnames: True
      enable_nat_gateway: True
      egress_via_nat_gateway: True
      nat_gateway_allocation_id: eipalloc-0fd0c117569440a4f  # 5.60.96.8
      nat_gateway_secondary_allocation_ids:
        - eipalloc-037682d640024609a  # 5.60.96.9
        - eipalloc-014cf4b0ce1d34629  # 5.60.96.10
        - eipalloc-0055539e4d56176f1  # 5.60.96.11
      endpoint_interfaces:
        - secretsmanager
      peering_connections:
        fluentbit-prod:
          peered_cidrs:
            - 10.200.0.0/22
          peer_vpc_id: vpc-028ee60c9e7f6b28e
          auto_accept: True  # Requires both VPCs to be in same account and region
          # Allow resolution of DNS records to private IPs (so we can use a private LB)
          accepter:
            allow_remote_vpc_dns_resolution: True
          requester:
            allow_remote_vpc_dns_resolution: True
      additional_routes:
        private:
          - destination_cidr_block: 10.10.0.0/16  # accounts-prod
            vpc_peering_connection_id: pcx-0fdcc9b776a069d2d
          - destination_cidr_block: 10.200.0.0/22  # fluentbit-prod
            vpc_peering_connection_id: pcx-0d581e66566a6e00b
        public: []

      # Dynamic values set in code, or not at all:
      # source_cidrs: []
      # source_sgids: []
      # subnets: []

  tb:ec2:SshableInstance:
    bastion:
      ssh_keypair_name: mailstrom-prod
      source_cidrs:
        - 38.15.46.29/32
  # Fill out this template to build an SSH bastion
  # tb:ec2:SshableInstance:
  #   bastion:
  #     ssh_keypair_name: your-ec2-keypair
  #     source_cidrs:
  #       - your.ip.addr.ess/32

  tb:mailstrom:StalwartCluster:
    thundermail:
      https_features:
        - caldav
        - carddav
        - jmap
      stalwart_image: stalwartlabs/stalwart:v0.15.4
      top_level_domain: thundermail.com
      redis_opts:
        apply_immediately: True
        automatic_failover_enabled: True
        cluster_mode: enabled
        description: Redis memory cache for Stalwart
        engine: redis
        engine_version: 7.1
        node_type: cache.t3.micro
        num_cache_nodes: 2
        parameter_group_family: redis7
        parameter_group_params:
          - name: cluster-enabled
            value: "yes"
        port: 6379
      nodes:
        "0": # Must be a unique, stringified integer
          disable_api_termination: True
          function: 'mail'
          ignore_ami_changes: True
          ignore_user_data_changes: True
          instance_type: t3a.large
          key_name: mailstrom-prod
          node_roles:
            - all
          services:
            - https
            - imaps
            - lmtp
            - managesieve
            - smtp
            - smtps
            - submission
          storage_capacity: 20
        "1": # Must be a unique, stringified integer
          disable_api_termination: True
          function: 'mail'
          ignore_ami_changes: True
          ignore_user_data_changes: True
          instance_type: t3a.large
          key_name: mailstrom-prod
          node_roles:
            - all
          services:
            - https
            - imaps
            - lmtp
            - managesieve
            - smtp
            - smtps
            - submission
          storage_capacity: 20
        "50":
          disable_api_termination: True
          function: 'api'
          ignore_ami_changes: True
          ignore_user_data_changes: True
          instance_type: t3.micro
          key_name: mailstrom-prod
          node_roles:
            - all
          services:
            - management
          storage_capacity: 20
          subnet: subnet-0b7564960babec972

      public_load_balancer:
        excluded_nodes: [ "50" ]
        services:
          https:
            source_cidrs: ['0.0.0.0/0']
          imaps:
            source_cidrs: ['0.0.0.0/0']
          lmtp:
            source_cidrs: ['0.0.0.0/0']
          managesieve:
            source_cidrs: ['0.0.0.0/0']
          smtp:
            source_cidrs: ['0.0.0.0/0']
          smtps:
            source_cidrs: ['0.0.0.0/0']
          submission:
            source_cidrs: ['0.0.0.0/0']

      private_load_balancers:
        management:
          excluded_nodes: ["0", "1"]
          source_security_group_ids:
            - sg-034b36952ac31b87b  # accounts-prod api container
            - sg-0ede6c1f9f8a4b676  # accounts-prod celery container

      spam_filter:
        bayes:
          account:
            enable: true # Enables per-account spam training
        score:
          spam: "8.0" # Minimum score to put email in Junk folder

      jmap:
        account:
          purge:
            frequency: "0 0 *"
        email:
          auto-expunge: 30d
        event-source:
          throttle: 1s
        protocol:
          changes:
            max-history: 30d
            max-results: 5000
          email:
            max-attachment-size: 50000000
            max-size: 75000000
          get:
            max-objects: 500
          mailbox:
            max-depth: 10
            max-name-length: 255
          parse:
            max-items: 10
          query:
            max-results: 5000
          set:
            max-objects: 500
          upload:
            max-concurrent: 4
            max-size: 50000000
            quota:
              files: 1000
              size: 50000000
            ttl: 1h
        push:
          attempts:
            interval: 1m
            max: 3
          max-total: 100
          retry:
            interval: 1s
          throttle: 1ms
          timeout:
            request: 10s
            verify: 1s
        rate-limit:
          account: 1000/1m
          anonymous: 100/1m
        websocket:
          heartbeat: 1m
          throttle: 1s
          timeout: 10m

  tb:s3:S3PrivateBucket:
    autoconfig:
      bucket_name: tb-mailstrom-prod-autoconfig-site
      object_dir: static-prod

  tb:cloudfront:CloudFrontDistribution:
    autoconfig:
      # cache_policy_id: set in code
      certificate_arn: arn:aws:acm:us-east-1:768512802988:certificate/df42b053-fe2f-4956-9fd9-45b9a12ccc1c
      distribution:
        aliases:
          - autoconfig.thundermail.com
        comment: mailstrom-prod autoconfig
        default_cache_behavior:
          allowed_methods:
            - GET
            - HEAD
            - OPTIONS
          cached_methods:
            - GET
            - HEAD
          compress: True
          # origins: set in code
          # target_origin_id: set in code
          viewer_protocol_policy: redirect-to-https
        enabled: True
        restrictions:
          geo_restriction:
            restriction_type: none
        default_root_object: thundermail.com.xml
      forcibly_destroy_bucket: True
      logging_bucket_name: tb-mailstrom-prod-autoconfig-logs

  tb:cloudwatch:CloudWatchMonitoringGroup:
    alarms: {}
    notify_emails:
      - thunderbird-services-monitoring+mailstrom-prod@thunderbird.net
    # alarms:
    #   alarm_group_name:
    #     alarm_name:
    #       enabled: False
    #       threshold: 80
    #       other_options: etc
