# Common const

# Prefix used when creating mailboxes/folders/messages
TEST_MSG_MIME_VER = '1.0'
CONTENT_TYPE_MULTI_MIXED = 'multipart/mixed'
CONTENT_TYPE_TEXT_PLAIN_UTF = 'text/plain; charset="utf-8"'
CONTENT_TYPE_TEXT_PLAIN_ASCII = 'text/plain; charset="us-ascii"'
CONTENT_TYPE_TEXT_HTML = 'text/html; charset="us-ascii"'
CONTENT_TYPE_PNG = 'image/png'
TRANS_ENCODING_7BIT = '7bit'
TRANS_ENCODING_BASE64 = 'base64'
CONTENT_DISP_ATTACHMENT = 'attachment'

# Where the tests download email attchments (also add to .gitignore)
DOWNLOAD_EMAIL_ATTACHMENTS_PATH = 'test_files/downloaded/'

# Connection states
STATE_NONAUTH = 'NONAUTH'
STATE_AUTH = 'AUTH'
STATE_LOGOUT = 'LOGOUT'
STATE_SELECTED = 'SELECTED'

# Return values from IMAP commands
LOGOUT_BYE = 'BYE'
RESULT_OK = 'OK'
RESULT_NO = 'NO'
ALREADY_EXISTS = b'already exists'
NOT_FOUND = b'not found'
MISSING_ARGS = b'Missing arguments'
MAILBOX_CREATED = b'Mailbox created'
MAILBOX_SUBSCRIBED = b'Mailbox subscribed'
MAILBOX_ALREADY_SUBSCRIBED = b'Mailbox is already subscribed'
MAILBOX_ALREADY_UNSUBSCRIBED = b'Mailbox is already unsubscribed'
MAILBOX_DELETED = b'Mailbox deleted'
MAILBOX_UNSUBSCRIBED = b'Mailbox unsubscribed'
MAILBOX_NAME_MISSING = b'Missing mailbox name'
MAILBOX_NOT_EXIST = b'Mailbox does not exist'
MAILBOX_RENAMED = b'RENAME completed'
INVALID_FOLDER_NAME = b'Invalid folder name'
MAILBOX_HAS_CHILD = b'[HASCHILDREN] Mailbox has children'
MAILBOX_CLOSE_COMPLETED = b'CLOSE completed'
MAILBOX_CLOSE_ILLEGAL_STATE = 'command CLOSE illegal in state AUTH, only allowed in states SELECTED'
APPEND_COMPLETED = b'APPEND completed'
MSG_DELETED_FLAG = b'\\Deleted'
MSG_SEEN_FLAG = b'\\Seen'
MSG_COPIED = b'COPY completed'
MSG_COPY_SAME_LOCATION = b'Source and destination mailboxes are the same'

# Test message data
MAILBOX_PREFIX = 'AutoTest'
TEST_MSG_SUBJECT_PREFIX = 'Mailstrom AutoTest'
TEST_MSG_DEL_SUBJECT_PREFIX = 'Automated test message allocated for deletion'
TEST_MSG_WITH_ATTACHMENT_SUBJECT_PREFIX = 'Attachment included in this test message'
TEST_MSG_BODY_PREFIX = 'Generated by the mailstrom tests.'
TEST_MSG_BODY_PREFIX_HTML = '<html><body><h1>Generated by the mailstrom tests (HTML).</h1></body></html>'
TEST_MSG_ATTACHMENT = './test_files/free_your_inbox.png'
ADDRESSBOOK_PREFIX = 'AutoTest Address Book'

# Test calendar data
CALENDAR_PREFIX = 'AutoTest Calendar'
EVENT_PREFIX = 'AutoTest Event'
TASK_PREFIX = 'AutoTest Task'
TASK_STATUS_NEEDS_ACTION = 'NEEDS-ACTION'
TASK_STATUS_COMPLETED = 'COMPLETED'
TASK_PRIORITY_HIGH = 1
TASK_PRIORITY_MEDIUM = 5
TASK_CATEGORY_FAVOURITES = 'Favourites'
TASK_CATEGORY_BUSINESS = 'Business'
TASK_CATEGORY_VACATION = 'Vacation'

# Test address book data
ADDRESS_BOOK_PREFIX = 'AutoTest Address Book'

# Timeouts
TEST_SLEEP_1_SECOND = 1
