import os
from dotenv import find_dotenv, load_dotenv

# Load our env
load_dotenv(find_dotenv('.env.test'), override=True)

# Mailstrom test server connection info
TEST_SERVER_HOST = str(os.getenv('TEST_SERVER_HOST')).strip()
IMAP_PORT = int(os.getenv('TEST_IMAP_PORT'))
SMTP_HOST = str(os.getenv('TEST_SMTP_HOST')).strip()
SMTP_PORT = int(os.getenv('TEST_SMTP_PORT'))
CONNECT_TIMEOUT = 10  # seconds

# Test accounts that already exist
TEST_ACCT_1_USERNAME = str(os.getenv('TEST_ACCT_1_USERNAME')).strip()
TEST_ACCT_1_PASSWORD = str(os.getenv('TEST_ACCT_1_PASSWORD')).strip()
TEST_ACCT_1_EMAIL = str(os.getenv('TEST_ACCT_1_EMAIL')).strip()

TEST_ACCT_2_USERNAME = str(os.getenv('TEST_ACCT_2_USERNAME')).strip()
TEST_ACCT_2_PASSWORD = str(os.getenv('TEST_ACCT_2_PASSWORD')).strip()
TEST_ACCT_2_EMAIL = str(os.getenv('TEST_ACCT_2_EMAIL')).strip()

# Default mailboxes expected to exist
DEFAULT_MAILBOX_LIST = [
    {'flags': '()', 'separator': '"/"', 'name': 'Deleted Items'},
    {'flags': '()', 'separator': '"/"', 'name': 'Drafts'},
    {'flags': '()', 'separator': '"/"', 'name': 'INBOX'},
    {'flags': '()', 'separator': '"/"', 'name': 'Junk Mail'},
    {'flags': '()', 'separator': '"/"', 'name': 'Sent Items'},
]

# Prefix used when creating mailboxes/folders
MAILBOX_PREFIX = 'AutoTest'

# Number of emails required in the inbox for the IMAP messaging tests, and their details
IMAP_MSG_TESTS_EMAIL_COUNT = 5
IMAP_MSG_TESTS_DRAFT_EMAIL_COUNT = 1
IMAP_MSG_TESTS_DEL_EMAIL_COUNT = 3
IMAP_MSG_TESTS_EMAIL_WITH_ATTACHMENT_COUNT = 1
TEST_MSG_SUBJECT_PREFIX = 'Mailstrom AutoTest'
TEST_MSG_DEL_SUBJECT_PREFIX = 'Automated test message allocated for deletion'
TEST_MSG_BODY_PREFIX = 'Generated by the mailstrom integration tests.'
TEST_MSG_MIME_VER = '1.0'
TEST_MSG_ATTACHMENT = './test_files/free_your_inbox.png'
TEST_MSG_WITH_ATTACHMENT_SUBJECT_PREFIX = 'Attachment included in this test message'
CONTENT_TYPE_MULTI_MIXED = 'multipart/mixed'
CONTENT_TYPE_TEXT_PLAIN = 'text/plain; charset="utf-8"'
CONTENT_TYPE_PNG = 'image/png'
TRANS_ENCODING_7BIT = '7bit'
TRANS_ENCODING_BASE64 = 'base64'
CONTENT_DISP_ATTACHMENT = 'attachment'

# Where the tests download email attchments (also add to .gitignore)
DOWNLOAD_EMAIL_ATTACHMENTS_PATH = './test_files/downloaded/'

# Connection states
STATE_NONAUTH = 'NONAUTH'
STATE_AUTH = 'AUTH'
STATE_LOGOUT = 'LOGOUT'
STATE_SELECTED = 'SELECTED'

# Return values from IMAP commands
LOGOUT_BYE = 'BYE'
RESULT_OK = 'OK'
RESULT_NO = 'NO'
ALREADY_EXISTS = b'already exists'
NOT_FOUND = b'not found'
MISSING_ARGS = b'Missing arguments'
MAILBOX_CREATED = b'Mailbox created'
MAILBOX_SUBSCRIBED = b'Mailbox subscribed'
MAILBOX_ALREADY_SUBSCRIBED = b'Mailbox is already subscribed'
MAILBOX_ALREADY_UNSUBSCRIBED = b'Mailbox is already unsubscribed'
MAILBOX_DELETED = b'Mailbox deleted'
MAILBOX_UNSUBSCRIBED = b'Mailbox unsubscribed'
MAILBOX_NAME_MISSING = b'Missing mailbox name'
MAILBOX_NOT_EXIST = b'Mailbox does not exist'
MAILBOX_RENAMED = b'RENAME completed'
INVALID_FOLDER_NAME = b'Invalid folder name'
MAILBOX_HAS_CHILD = b'Mailbox has at least one children'
MAILBOX_CLOSE_COMPLETED = b'CLOSE completed'
MAILBOX_CLOSE_ILLEGAL_STATE = 'command CLOSE illegal in state AUTH, only allowed in states SELECTED'
APPEND_COMPLETED = b'APPEND completed'
MSG_DELETED_FLAG = b'\\Deleted'
MSG_SEEN_FLAG = b'\\Seen'
MSG_COPIED = b'COPY completed'
MSG_COPY_SAME_LOCATION = b'Source and destination mailboxes are the same'
